site_name: PG-RAD Documentation
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: blue
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: light blue
      accent: blue
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
- mkdocs-jupyter:
    execute: false
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    default_handler: python
    locale: en
    handlers:
      python:
        options:
          show_source: false
          show_root_heading: false

nav:
  - Home: index.md
  - Installation Guide: installation.md
  - Quickstart Guide: quickstart.md
  - 'Tutorial: Writing a Config File': config-spec.md
  - Explainers:
    - explainers/planar_curve.ipynb
    - explainers/prefab_roads.ipynb
    - explainers/count_rate_along_path.ipynb
  - Thesis: explainers/Nelissen_Pim_Thesis_MORC_PGRAD.pdf