[build-system]
requires = ["setuptools>=64.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"pg_rad.data" = ["*.csv"]
"pg_rad.configs" = ["*.yml"]

[project]
name = "pg-rad"
version = "0.2.1"
authors = [
  { name="Pim Nelissen", email="pi0274ne-s@student.lu.se" },
]
description = "Primary Gamma RADiation Landscape"
readme = "README.md"
requires-python = ">=3.12.4,<3.13"
dependencies = [
    "matplotlib>=3.9.2",
    "numpy>=2",
    "pandas>=2.3.1",
    "pyyaml>=6.0.2",
    "scipy>=1.15.0"
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.scripts]
pgrad = "pg_rad.main:main"

[project.urls]
Homepage = "https://github.com/pim-n/pg-rad"
Issues = "https://github.com/pim-n/pg-rad/issues"

[project.optional-dependencies]

dev = ["pytest", "mkinit", "notebook", "mkdocs-material", "mkdocstrings-python", "mkdocs-jupyter", "flake8"]